<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzom7a9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzom7a9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYzom7a9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYzom7a9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYzom7a9\appProdProjectContainer([
    'container.build_hash' => 'Yzom7a9',
    'container.build_id' => 'd60d866a',
    'container.build_time' => 1558510266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzom7a9');
