<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcjktzt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcjktzt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWcjktzt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWcjktzt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWcjktzt\appProdProjectContainer([
    'container.build_hash' => 'Wcjktzt',
    'container.build_id' => 'd1dc5ae1',
    'container.build_time' => 1557722903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcjktzt');
