<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyzwffi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyzwffi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYyzwffi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYyzwffi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYyzwffi\appDevDebugProjectContainer([
    'container.build_hash' => 'Yyzwffi',
    'container.build_id' => '89345a88',
    'container.build_time' => 1554717308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyzwffi');
